### ISSUE TITLE
Implement custom JS/CSS for LibCal to hide/disable CU Events advertising field from public view

### ISSUE THREAD

**Issue by cappadona** [cul-it/mann-wagon#860]
Once/if this is in place, #857 should be reverted.

**Comment by cappadona** [comment]
Added custom css to hide field from public view of **Mann Conference Room** form and confirmed the field is still accessible to admins when editing a booking. A bit of a hack since LibCal doesn't provide a `class` or `id` that can be used to target this single field:

```css
/* Hide de-dupe/suppress field from public on Mann Conference Room booking form
   * lobby (13987)
   * rm 100 (13988)
   * rm 102 (13989)
   * stone classroom (12377)
   * terrace (15431)
   ****************************************/
  body#s-lc-rm-13987 div.form-group.s-lc-rm-q.s-lc-8,
  body#s-lc-rm-13988 div.form-group.s-lc-rm-q.s-lc-8,
  body#s-lc-rm-13989 div.form-group.s-lc-rm-q.s-lc-8,
  body#s-lc-rm-12377 div.form-group.s-lc-rm-q.s-lc-8,
  body#s-lc-rm-15431 div.form-group.s-lc-rm-q.s-lc-8 {
    display: none;
  } 
```

![screenshot 2017-08-10 10 43 00](https://user-images.githubusercontent.com/409842/29176077-d9ced120-7db8-11e7-8a59-e94fd3a00d58.png)
